config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#home'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'friends', to: 'users#friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  # makes sure to have a valid symbol when saving to database
  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: '',
        endpoint: ''
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.user_search(param)
    # Will get rid of any blank spaces in search
    param.strip!
    # see if param matches any of the fields, concatenates them, and returns only the unique values
    # so you will not receive duplicates
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    # if it there is nothing to return it will return nil otherwise it will return the matched value
    return nil unless to_send_back
    to_send_back
  end

  # these matches methods are what will be called with the appropriate field name for user_search
  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  # excludes the logged in user from displaying on the search dropdown
  def except_current_user(users)
    # this rejects any user whose id matches the current user
    users.reject { |user| user.id == self.id }
  end

  # If the current user is already friends with a user on their search list it will not show the option to follow friends
  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end


  # Takes in field name and searches for a match based on a similar string
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "New friend!"
    else
      flash[:notice] = "No new friend"
    end
    redirect_to friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Friend deleted"
    redirect_to friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter in a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter in a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  # Check to see if the stock already exists and if it doesn't then lookup the stock, save it,
  # and then create a new association of the stock with the current user
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
      @user_stock = UserStock.create(user: current_user, stock: stock)
      flash[:notice] = "Stock #{stock.name} was successfully added to you portfolio"
      redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_friends = current_user.friends
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.user_search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Could not find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter in a valid friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.erb
<p class="notice alert-success"><%= notice %></p>
<p class="alert alert-danger"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "FinanceTracker", root_path, class: 'navbar-brand nav-link' %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Portfolio", my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Friends", friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item user-name"><%= current_user.full_name %></li>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path,
                        class: 'btn btn-danger', method: :delete) %>
          </li>
        </ul>
        <!--      <form class="form-inline my-2 my-lg-0">-->
        <!--        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
        <!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--      </form>-->
      </div>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/message' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@tracked_stocks.empty? %>
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-dark table.hover">
        <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td><% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                            class: "btn btn-xs btn-success", method: :post %>
                <% elsif !current_user.id == @user.id %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit? %>
                      10 stocks
                    <% end %>
                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                      this stock
                    <% end %>
                  </span>
              <% end %>
            </td>
            <% if current_user.id == @user.id %>
            <td><%= link_to 'Delete', user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <p class="lead">Not tracking any stocks</p>
<% end %>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/message' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <% @friends.each do |friend| %>
      <ul>
        <li>
          <strong>Name: </strong> <%= friend.full_name %>
          <strong>Email: </strong> <%= friend.email %>
          <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
          <% if current_user.not_friends_with?(friend.id) %>
          <%= link_to 'Follow friend?', friendships_path(friend: friend),
                      class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">You are friends</span>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/message' %>
</div>


<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Company: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                  class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
// This grabs from the div with id of results and renders the info in the result html partial
// In ruby the j escapes the javascript
  // Could also do escape_javascript(render '')
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/friends.html.erb
<h1>Friends</h1>

<div class="search-area">
  <h3>Search Friends</h3>
  <!--  Adding remote: true, turns it into an ajax request-->
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Search Name or Email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">

</div>


<% if !@friends.empty? %>

  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-dark table.hover">
        <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
        </tr>
        </thead>
        <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.first_name + ' ' + friend.last_name %></td>
            <td> <%= friend.email %> </td>
            <td><%= link_to "View Profile", user_path(friend), class: "btn btn-success" %></td>
            <td><%= link_to 'Stop Following', friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>

  <h2>You currently do not have any friends listed</h2>

<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
<!--  Adding remote: true, turns it into an ajax request-->
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">

</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <ul>
    <li>
      <strong>Name: </strong> <%= @user.full_name %>
      <strong>Email: </strong> <%= @user.email %>
      <% if current_user.not_friends_with?(@user.id) %>
        <%= link_to 'Follow friend?', friendships_path(friend: @user),
                    class: "btn btn-sm btn-success", method: :post %>
      <% else %>
        <span class="badge badge-secondary">You are friends</span>
      <% end %>
    </li>
  </ul>
</div>


<%= render 'stocks/list' %>

app/views/welcome/home.html.erb
<h1>This is the homepage for Finance Tracker</h1>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>